name: gym_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip
  - pip:
      - streamlit>=1.30
      - mediapipe>=0.10
      - opencv-python        # usa "opencv-python-headless" si lo correrás en servidor sin GUI
