"""Regression tests for the exported metrics CSV."""

import os

import pandas as pd

METRICS_CSV = "data/processed/poses/1-Squat_Own_metrics.csv"


def test_metrics_csv_exists():
    """Verify that the metrics CSV generated by the ``metrics`` subcommand exists."""
    assert os.path.isfile(METRICS_CSV), f"Metrics file not found: {METRICS_CSV}"


def test_metrics_csv_columns():
    """Ensure the metrics CSV exposes the expected minimum set of columns."""
    df = pd.read_csv(METRICS_CSV)
    expected_cols = {
        "frame_idx",
        "left_knee",
        "right_knee",
        "left_elbow",
        "right_elbow",
        "shoulder_width",
        "foot_separation",
        "ang_vel_left_knee",
        "ang_vel_right_knee",
        "ang_vel_left_elbow",
        "ang_vel_right_elbow",
        "knee_symmetry",
        "elbow_symmetry",
    }
    actual_cols = set(df.columns)
    missing = expected_cols - actual_cols
    assert not missing, f"Missing columns in metrics CSV: {missing}"
    assert len(df) > 0, "Metrics CSV is empty."
