[theme]
base="dark"
primaryColor="#22c55e"       # green for primary buttons (Continue / Analyze)
secondaryColor="#ef4444"    # red for secondary actions (Back)
backgroundColor="#0f172a"
secondaryBackgroundColor="#111827"
textColor="#e5e7eb"
